training:
  start_epoch: 0
  resume: True
  num_epochs: 50
  # batch_size: 32
  batch_size: 32
  device: 'cuda:0'
  checkpoint_interval: 1
  checkpoint_dir: '/mnt/DATA2/dorin/Image-Transform-Predict/checkpoints/itp_vit_tune_full'

data:
  tensorboard_logdir: '/mnt/DATA2/dorin/Image-Transform-Predict/logs/itp_vit_tune_full'

model:
  model_name: 'itp_vit'
  # initialization_weights_path: null
  initialization_weights_path: "/mnt/DATA2/dorin/Image-Transform-Predict/checkpoints/itp_vit/model_weights.pth"
  encoder:
    type: 'vit'
    freeze_image_encoder: False
    out_token_n_embd: 512
  decoder:
    pos_encoding: 'learned'
    rope_base: null
    activation: 'gelu'
    n_embd: 512
    ffn_ratio: 4
    n_head: 8
    n_layer: 3
    max_seq_len: 15
    dropout: 0.1
    bias: False
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 0
    vocab_size: 14

optimizer:
  name: 'AdamW'
  # lr: 0.001
  lr: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  milestones: [20, 40]
  gamma: 0.5

augmentation:
  initial_p: 0.3
  milestones: []
  probs: []