training:
  start_epoch: 0
  resume: True
  num_epochs: 50
  batch_size: 16
  device: 'cuda:1'
  checkpoint_interval: 1
  checkpoint_dir: '/home/jovyan/nkiselev/ddorin/project/Image-Transform-Predict/checkpoints/itp_002'

data:
  tensorboard_logdir: '/home/jovyan/nkiselev/ddorin/project/Image-Transform-Predict/logs/itp_002'

model:
  model_name: 'itp_002'
  initialization_weights_path: null
  encoder:
    encoder_emb_dim: null
    freeze_image_encoder: False
    combined_emb_dim: 512
    use_fuser: True
  decoder:
    n_embd: 512
    n_hidden_state: 2048
    n_head: 8
    n_layer: 3
    max_seq_len: 15
    dropout: 0.1
    bias: False
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 0
    vocab_size: 14

optimizer:
  name: 'AdamW'
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  milestones: [5, 10]
  gamma: 0.5